version: "3"
services:
  web:
    image: wuyy1234/wyy_angular_demo
    deploy:
      replicas: 5
      resources:
        limits: 
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8111:4200"
    networks: 
      - gowebnet
networks: 
  gowebnet:
